# Generated by Django 4.2 on 2023-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource', verbose_name='Fotos aktuell')),
                ('title', models.CharField(max_length=100, verbose_name='Vergaldungen')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='Inhalt')),
                ('button', models.CharField(max_length=100, verbose_name='Schaltfläche')),
                ('link', models.CharField(max_length=300, verbose_name='Der Link')),
            ],
            options={
                'verbose_name': 'Aktuelles',
                'verbose_name_plural': 'Aktuelle',
            },
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Freitag',
                'verbose_name_plural': 'Freitage',
            },
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Montag',
                'verbose_name_plural': 'Montage',
            },
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Samstag',
                'verbose_name_plural': 'Samstage',
            },
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Sonntag',
                'verbose_name_plural': 'Sonntage',
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Donnerstag',
                'verbose_name_plural': 'Donnerstage',
            },
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Dienstag',
                'verbose_name_plural': 'Dienstage',
            },
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name='Zeit')),
                ('numbers', models.CharField(verbose_name='Zahl')),
                ('name_of_the_teachers', models.TextField(blank=True, max_length=200, verbose_name='Name der Lehrer')),
            ],
            options={
                'verbose_name': 'Mittwoch',
                'verbose_name_plural': 'Medien',
            },
        ),
    ]
