# Generated by Django 4.2 on 2023-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_actual_button_alter_actual_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Inhalt'),
        ),
    ]
