# Generated by Django 4.2 on 2023-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_actual_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Vergaldungen')),
                ('content', models.TextField(max_length=5000, verbose_name='Inhalt')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Der Link')),
            ],
            options={
                'verbose_name': 'Aktuelle Button',
                'verbose_name_plural': 'Aktuelles Buttons',
            },
        ),
        migrations.AlterModelOptions(
            name='actual',
            options={'verbose_name': 'Aktuelle', 'verbose_name_plural': 'Aktuelles'},
        ),
        migrations.AlterField(
            model_name='actual',
            name='link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Der Link'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vergaldungen'),
        ),
    ]
