# Generated by Django 4.2 on 2023-07-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_actualbutton_alter_actual_options_alter_actual_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualbutton',
            options={'verbose_name': 'Aktuelle_Button', 'verbose_name_plural': 'Aktuelles_Buttons'},
        ),
    ]
