# Generated by Django 4.2 on 2023-07-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_alter_actualbutton_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sunday',
        ),
    ]
