# Generated by Django 4.2 on 2023-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_delete_sunday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualButtonFourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Vergaldungen')),
                ('content', models.TextField(max_length=5000, verbose_name='Inhalt')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Der Link')),
            ],
            options={
                'verbose_name': 'Aktuelle_Button',
                'verbose_name_plural': 'Aktuelles_Buttons',
            },
        ),
        migrations.CreateModel(
            name='ActualButtonOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Vergaldungen')),
                ('content', models.TextField(max_length=5000, verbose_name='Inhalt')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Der Link')),
            ],
            options={
                'verbose_name': 'Aktuelle_Button',
                'verbose_name_plural': 'Aktuelles_Buttons',
            },
        ),
        migrations.CreateModel(
            name='ActualButtonThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Vergaldungen')),
                ('content', models.TextField(max_length=5000, verbose_name='Inhalt')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Der Link')),
            ],
            options={
                'verbose_name': 'Aktuelle_Button',
                'verbose_name_plural': 'Aktuelles_Buttons',
            },
        ),
        migrations.CreateModel(
            name='ActualButtonTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Vergaldungen')),
                ('content', models.TextField(max_length=5000, verbose_name='Inhalt')),
                ('link', models.CharField(blank=True, max_length=1000, verbose_name='Der Link')),
            ],
            options={
                'verbose_name': 'Aktuelle_Button',
                'verbose_name_plural': 'Aktuelles_Buttons',
            },
        ),
        migrations.RenameModel(
            old_name='ActualButton',
            new_name='ActualButtonFifth',
        ),
    ]
