# Generated by Django 4.2 on 2023-07-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_actualbuttonfourth_actualbuttonone_actualbuttonthird_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualbuttonfifth',
            options={'verbose_name': 'weitere Nachrichten Nr.5', 'verbose_name_plural': 'weitere Nachrichten Nr.5'},
        ),
        migrations.AlterModelOptions(
            name='actualbuttonfourth',
            options={'verbose_name': 'weitere Nachrichten Nr.4', 'verbose_name_plural': 'weitere Nachrichten Nr.4'},
        ),
        migrations.AlterModelOptions(
            name='actualbuttonone',
            options={'verbose_name': 'weitere Nachrichten Nr.1', 'verbose_name_plural': 'weitere Nachrichten Nr.1'},
        ),
        migrations.AlterModelOptions(
            name='actualbuttonthird',
            options={'verbose_name': 'weitere Nachrichten Nr.3', 'verbose_name_plural': 'weitere Nachrichten Nr.3'},
        ),
        migrations.AlterModelOptions(
            name='actualbuttontwo',
            options={'verbose_name': 'weitere Nachrichten Nr.2', 'verbose_name_plural': 'weitere Nachrichten Nr.2'},
        ),
    ]
